### ISSUE TITLE
Microservices download not available on NGC

### ISSUE THREAD

**Issue by PushkarChatterji** [NVIDIA-AI-IOT/mmj_genai#1]
Your link to the microservices pops a 404 error on NGC.

Yep, I have signed up.
Yep, I have been given access. 
And Yep, we are part of the Inception Program and are a Metropolis Partner.

**Comment by ssmmoo1** [comment]
Hello,

Could you reply with the exact link that is giving you the 404 error? 

Thanks,
Sammy Ochoa
